export const concurrentMaintenanceSearchContent = {
  description:
    'Monitor and manage concurrent maintenance operations for hardware components without system downtime',
  features: [
    'View concurrent maintenance status for system components',
    'Monitor hardware replacement operations',
    'Track hot-plug component activities',
    'View maintenance mode status',
    'Monitor field replaceable unit (FRU) operations',
    'Check component serviceability status',
    'View concurrent repair operations',
    'Track hardware maintenance history',
  ],
  keywords: [
    'concurrent maintenance',
    'hot swap',
    'hot plug',
    'hardware replacement',
    'FRU',
    'field replaceable unit',
    'maintenance mode',
    'component replacement',
    'hardware service',
    'concurrent repair',
    'serviceability',
    'online maintenance',
    'live maintenance',
    // Natural language variations
    'show concurrent maintenance',
    'view concurrent maintenance',
    'display concurrent maintenance',
    'monitor concurrent maintenance',
    'check concurrent maintenance',
    'where is concurrent maintenance',
    'hot swap components',
    'hot plug devices',
    'replace hardware',
    'swap hardware',
    'change components',
    'replace components',
    'show FRU',
    'view FRU',
    'field replaceable units',
    'replaceable components',
    'show maintenance status',
    'view maintenance status',
    'check maintenance status',
    'maintenance operations',
    'hardware maintenance',
    'component service',
    'service hardware',
    'repair hardware',
    'online repair',
    'live repair',
    'zero downtime',
    'no downtime',
    'without downtime',
    'replace without shutdown',
    'swap without shutdown',
  ],
  relatedTerms: [
    'hardware maintenance',
    'component service',
    'hot-swappable',
    'concurrent operations',
    'maintenance status',
    'hardware repair',
    'component serviceability',
    'online repair',
    'live replacement',
    'zero downtime maintenance',
  ],
};

export default concurrentMaintenanceSearchContent;
