export const sensorsSearchContent = {
  // Main description
  description:
    'Display sensor information including Name, Status, and Current value. Filter sensors by status values (OK, Warning, Critical) to monitor system health and performance.',

  // Feature descriptions
  features: [
    'Sensor monitoring',
    'Temperature sensor readings',
    'Voltage sensor readings',
    'Fan speed monitoring',
    'Power sensor readings',
    'Critical threshold monitoring',
    'Warning threshold monitoring',
    'Sensor status tracking',
    'Real-time sensor data',
    'Sensor health monitoring',
    'Display sensor Name',
    'Display sensor Status',
    'Display Current value',
    'Click Filter to apply status',
    'Filter by OK status',
    'Filter by Warning status',
    'Filter by Critical status',
    'Select status values',
    'Apply status filters',
  ],

  // Searchable keywords
  keywords: [
    'sensors',
    'temperature',
    'voltage',
    'fan',
    'speed',
    'power',
    'reading',
    'threshold',
    'critical',
    'warning',
    'monitoring',
    'sensor status',
    'sensor reading',
    'temperature sensor',
    'voltage sensor',
    'fan sensor',
    'power sensor',
    'upper critical',
    'lower critical',
    'upper warning',
    'lower warning',
    'current value',
    'sensor name',
    'display name',
    'display status',
    'display current value',
    'click filter',
    'apply filter',
    'filter status',
    'status values',
    'OK status',
    'Warning status',
    'Critical status',
    'filter by OK',
    'filter by Warning',
    'filter by Critical',
    'select status',
    'available options',
    'status filter',
    'sensor filter',
  ],

  // Related terms
  relatedTerms: [
    'hardware monitoring',
    'system monitoring',
    'thermal monitoring',
    'environmental monitoring',
    'sensor data',
    'telemetry',
    'system health',
    'status filtering',
    'filter options',
    'health status',
    'sensor health',
    'status selection',
    'filter application',
    'status display',
    'value display',
    'name display',
  ],
};

export default sensorsSearchContent;
