export const profileSettingsSearchContent = {
  description:
    'Manage user profile settings including timezone, language preferences, and session timeout configurations',
  features: [
    'Configure timezone settings for the user interface',
    'Set language and locale preferences',
    'Adjust session timeout duration',
    'Customize user interface preferences',
    'Update personal account settings',
    'Manage notification preferences',
  ],
  keywords: [
    'profile',
    'settings',
    'preferences',
    'user settings',
    'account settings',
    'timezone',
    'language',
    'locale',
    'session timeout',
    'personalization',
    'user preferences',
    'interface settings',
    'notifications',
    // Natural language variations
    'show profile settings',
    'view profile settings',
    'display profile settings',
    'configure profile',
    'setup profile',
    'edit profile',
    'modify profile',
    'change profile',
    'update profile',
    'where is profile settings',
    'my profile',
    'my settings',
    'my preferences',
    'user profile',
    'account preferences',
    'show timezone',
    'view timezone',
    'set timezone',
    'change timezone',
    'configure timezone',
    'time zone settings',
    'show language',
    'view language',
    'set language',
    'change language',
    'configure language',
    'language settings',
    'show session timeout',
    'view session timeout',
    'set session timeout',
    'change session timeout',
    'configure session timeout',
    'timeout settings',
    'personalize interface',
    'customize interface',
    'interface preferences',
    'notification settings',
    'notification preferences',
  ],
  relatedTerms: [
    'user profile',
    'account configuration',
    'personal settings',
    'UI preferences',
    'localization',
    'time zone',
    'session management',
    'user customization',
  ],
};

export default profileSettingsSearchContent;
