export const fieldCoreOverrideSearchContent = {
  // Main description
  description:
    'View or change the processor cores that will be configured by the firmware. View current configuration including total installed cores, licensed cores, and configured cores. Enable field core override and set configured cores value (minimum 1). Changes take effect on next server reboot.',

  // Feature descriptions
  features: [
    'View processor core configuration',
    'Change processor cores configured by firmware',
    'Current configuration display',
    'Total installed cores information',
    'Licensed cores information',
    'Configured cores information',
    'Change configuration settings',
    'Enable field core override',
    'Configure cores value entry',
    'Minimum 1 core requirement',
    'Server reboot requirement for changes',
    'Configuration save functionality',
    'Successfully saved confirmation message',
    'Field core override enable/disable',
    'Processor core management',
  ],

  // Searchable keywords
  keywords: [
    'field',
    'core',
    'override',
    'processor',
    'processor cores',
    'field core',
    'core override',
    'field core override',
    'processor core',
    'configured by firmware',
    'firmware',
    'current configuration',
    'total installed cores',
    'installed cores',
    'licensed cores',
    'configured cores',
    'change configuration',
    'enable field core override',
    'enable override',
    'configured cores value',
    'minimum 1',
    'at least 1',
    'core value',
    'enter configured cores',
    'server reboot',
    'next reboot',
    'changes take effect',
    'applying changes',
    'configuration saved',
    'successfully saved',
    'save configuration',
    'core configuration',
    'core settings',
    'core management',
    'view configuration',
    'change cores',
    'core activation',
    'configuration details',
  ],

  // Related terms
  relatedTerms: [
    'processor management',
    'core configuration',
    'CPU configuration',
    'processor settings',
    'core control',
    'processor activation',
    'system reboot',
    'firmware configuration',
    'resource management',
    'processor resources',
    'core allocation',
    'hardware configuration',
    'system configuration',
  ],
};

export default fieldCoreOverrideSearchContent;
