export const systemParametersSearchContent = {
  // Main description
  description:
    'View or edit system parameters including lateral cast out, frequency cap (MHz), aggressive prefetch, runtime processor diagnostic (RPD) feature and policy, RPD scheduled run time, guard on error, and immediate test requests. Configure processor diagnostics with enabled, automatic (128GB memory), scheduled, or disabled modes.',

  // Feature descriptions
  features: [
    'Lateral cast out enable/disable',
    'Service provider instruction requirement',
    'System performance impact warning',
    'Frequency cap enable/disable',
    'Maximum operating frequency in MHz',
    'Frequency cap value configuration',
    'Aggressive prefetch enable/disable',
    'Processor favor aggressive prefetch',
    'Runtime processor diagnostic (RPD) feature',
    'RPD feature enabled mode',
    'RPD feature automatic mode (128GB memory)',
    'RPD feature disabled mode',
    'Update RPD feature',
    'Runtime processor diagnostic policy',
    'RPD policy enabled (periodic testing)',
    'RPD policy scheduled (daily at specific time)',
    'RPD policy disabled (no diagnostics)',
    'Update RPD policy',
    'RPD scheduled run time of day',
    'Start time in 24-hour UTC format',
    'Duration in minutes',
    'Update RPD schedule run',
    'Guard on error enable/disable',
    'Processor core de-configuration on error',
    'Immediate test requested',
    'Run now button for immediate diagnostic',
    'Override RPD policy',
    'Diagnostic test run start',
    'Stop diagnostic test run',
    'Button greyed out during test',
    'System powered on requirement',
    'Changes take effect on next reboot',
    'Successfully saved messages',
  ],

  // Searchable keywords
  keywords: [
    'system',
    'parameters',
    'system parameters',
    'lateral cast out',
    'lateral',
    'cast out',
    'enable lateral',
    'disable lateral',
    'service provider',
    'degrade performance',
    'system performance',
    'frequency cap',
    'frequency',
    'cap',
    'enable frequency cap',
    'disable frequency cap',
    'maximum operating frequency',
    'MHz',
    'frequency value',
    'save frequency',
    'aggressive prefetch',
    'aggressive',
    'prefetch',
    'enable aggressive',
    'disable aggressive',
    'processor favor',
    'runtime processor diagnostic',
    'RPD',
    'RPD feature',
    'runtime diagnostic',
    'processor diagnostics',
    'diagnostic feature',
    'enabled mode',
    'automatic mode',
    'disabled mode',
    '128GB',
    'installed memory',
    'update RPD feature',
    'RPD feature saved',
    'changes take effect',
    'next reboot',
    'runtime processor diagnostic policy',
    'RPD policy',
    'diagnostic policy',
    'enabled policy',
    'scheduled policy',
    'disabled policy',
    'periodic basis',
    'each core',
    'test cores',
    'scheduled time',
    'each day',
    'duration minutes',
    'no diagnostics',
    'no exercisers',
    'update RPD policy',
    'RPD policy saved',
    'RPD scheduled run time',
    'scheduled run time',
    'time of day',
    'start time',
    '24-hour time',
    'UTC',
    'duration',
    'minutes',
    'update RPD schedule',
    'updated RPD schedule',
    'guard on error',
    'guard',
    'enable guard',
    'disable guard',
    'processor core',
    'de-configured',
    'deconfigured',
    'on error',
    'immediate test',
    'test requested',
    'run now',
    'run now button',
    'override policy',
    'diagnostic test run',
    'start immediately',
    'greyed out',
    'button greyed',
    'test runs',
    'stop diagnostic',
    'stop test run',
    'diagnostic test run saved',
    'tests will start',
    'system powered on',
    'diagnostic test run stopped',
    'successfully saved',
    'successfully stopped',
    'save changes',
  ],

  // Related terms
  relatedTerms: [
    'system configuration',
    'performance optimization',
    'processor tuning',
    'system tuning',
    'performance settings',
    'processor configuration',
    'diagnostic testing',
    'core testing',
    'processor health',
    'system diagnostics',
    'error handling',
    'core management',
    'frequency management',
    'memory requirements',
    'scheduled tasks',
    'system maintenance',
    'processor exercisers',
  ],
};

export default systemParametersSearchContent;
