export const rebootBmcSearchContent = {
  // Main description
  description:
    'Reboot the Baseboard Management Controller (BMC), view last reboot time, and manage BMC restart operations',

  // Feature descriptions
  features: [
    'BMC reboot functionality',
    'Restart BMC controller',
    'View last BMC reboot time',
    'BMC restart confirmation',
    'System dump protection during reboot',
    'BMC connection management',
    'Web browser reconnection after reboot',
    'BMC online status monitoring',
    'Automatic login prompt after reboot',
    'BMC service restart',
    'Controller reset operation',
    'BMC power cycle',
  ],

  // Searchable keywords
  keywords: [
    'reboot',
    'BMC',
    'restart',
    'reset',
    'controller',
    'baseboard',
    'management controller',
    'reboot BMC',
    'restart BMC',
    'reset BMC',
    'BMC reboot',
    'BMC restart',
    'BMC reset',
    'last reboot',
    'reboot time',
    'BMC online',
    'BMC offline',
    'web browser',
    'connection',
    'reconnect',
    'login',
    'system dump',
    'dump offload',
    'confirm reboot',
    'BMC service',
    'controller restart',
    'power cycle',
    'BMC power',
    'service restart',
    'management controller reboot',
    'baseboard controller',
    'BMC maintenance',
    'controller maintenance',
  ],

  // Related terms
  relatedTerms: [
    'system restart',
    'controller reset',
    'service recovery',
    'BMC recovery',
    'management interface',
    'remote management',
    'out-of-band management',
    'IPMI restart',
    'controller refresh',
    'system maintenance',
    'BMC maintenance',
    'service interruption',
    'connection loss',
    'session timeout',
    'automatic reconnection',
    're-authentication',
    'login required',
    'BMC availability',
    'controller availability',
    'service downtime',
  ],
};

export default rebootBmcSearchContent;
