export const rebootBmcSearchContent = {
  // Main description
  description:
    'Reboot the Baseboard Management Controller (BMC) on a server. The Reboot BMC window displays the Last BMC reboot information. When you reboot the BMC, your web browser loses contact with the BMC for several minutes. When the BMC is back online, you may need to log in again.',

  // Feature descriptions
  features: [
    'BMC reboot functionality',
    'Restart BMC controller',
    'View last BMC reboot time',
    'BMC restart confirmation',
    'System dump protection during reboot',
    'BMC connection management',
    'Web browser reconnection after reboot',
    'BMC online status monitoring',
    'Automatic login prompt after reboot',
    'BMC service restart',
    'Controller reset operation',
    'BMC power cycle',
    'Reboot BMC on server',
    'Last BMC reboot information display',
    'Web browser loses contact during reboot',
    'BMC back online notification',
    'Re-login after BMC reboot',
    'Click Reboot BMC to restart',
    'Confirm to restart BMC',
    'Cancel BMC reboot operation',
  ],

  // Searchable keywords
  keywords: [
    'reboot',
    'BMC',
    'restart',
    'reset',
    'controller',
    'baseboard',
    'management controller',
    'reboot BMC',
    'restart BMC',
    'reset BMC',
    'BMC reboot',
    'BMC restart',
    'BMC reset',
    'last reboot',
    'reboot time',
    'BMC online',
    'BMC offline',
    'web browser',
    'connection',
    'reconnect',
    'login',
    'system dump',
    'dump offload',
    'confirm reboot',
    'BMC service',
    'controller restart',
    'power cycle',
    'BMC power',
    'service restart',
    'management controller reboot',
    'baseboard controller',
    'BMC maintenance',
    'controller maintenance',
    'reboot BMC on server',
    'last BMC reboot information',
    'loses contact',
    'browser loses contact',
    'BMC back online',
    'log in again',
    're-login',
    'click reboot BMC',
    'click confirm',
    'cancel reboot',
    'several minutes',
    'BMC window',
    'reboot information',
    'restart the BMC',
    'exit window',
  ],

  // Related terms
  relatedTerms: [
    'system restart',
    'controller reset',
    'service recovery',
    'BMC recovery',
    'management interface',
    'remote management',
    'out-of-band management',
    'IPMI restart',
    'controller refresh',
    'system maintenance',
    'BMC maintenance',
    'service interruption',
    'connection loss',
    'session timeout',
    'automatic reconnection',
    're-authentication',
    'login required',
    'BMC availability',
    'controller availability',
    'service downtime',
    'server BMC',
    'BMC contact lost',
    'browser disconnection',
    'temporary unavailability',
    'BMC recovery time',
    'reboot confirmation dialog',
    'cancel operation',
    'confirm restart',
    'BMC status window',
    'last reboot timestamp',
  ],
};

export default rebootBmcSearchContent;
