export const pcieTopologySearchContent = {
  // Main description
  description:
    'Display PCIe topology information including Id, Parent ID, Link status, Local port location, and Remote port location. Filter PCIe topology data by applying selected filter criteria.',

  // Feature descriptions
  features: [
    'PCIe topology viewing',
    'PCIe slot information',
    'PCIe link status',
    'Identify LED management',
    'PCIe link reset',
    'Hardware topology visualization',
    'PCIe device information',
    'Slot configuration',
    'Display Id information',
    'Display Parent ID',
    'Display Link status',
    'Display Local port location',
    'Display Remote port location',
    'Click Filter to apply selection',
    'Apply selected filters',
    'Filter PCIe topology data',
  ],

  // Searchable keywords
  keywords: [
    'PCIe',
    'PCI',
    'topology',
    'hardware',
    'slot',
    'link',
    'LED',
    'reset',
    'PCIe topology',
    'hardware topology',
    'PCIe slot',
    'PCIe link',
    'identify LED',
    'link reset',
    'PCIe device',
    'slot information',
    'link status',
    'Id',
    'Parent ID',
    'Link status',
    'Local port location',
    'Remote port location',
    'display Id',
    'display Parent ID',
    'display Link status',
    'display Local port',
    'display Remote port',
    'click filter',
    'apply filter',
    'selected filters',
    'filter criteria',
    'filter topology',
    'topology data',
    'port location',
    'local port',
    'remote port',
  ],

  // Related terms
  relatedTerms: [
    'hardware configuration',
    'device topology',
    'expansion slots',
    'PCIe configuration',
    'hardware layout',
    'device connections',
    'topology information',
    'parent identification',
    'port identification',
    'location information',
    'filter application',
    'data filtering',
    'topology filtering',
    'port details',
    'link information',
  ],
};

export default pcieTopologySearchContent;
