export const powerSearchContent = {
  // Main description
  description:
    'Manage power consumption, power cap settings, power and performance modes (Maximum performance, Energy efficient, Maximum energy saver), and idle power saver configurations with delay time and utilization thresholds',

  // Feature descriptions
  features: [
    'Current power consumption monitoring',
    'Power cap setting configuration',
    'Apply power cap option',
    'Power cap value in watts (0-4294967295)',
    'Power and performance mode selection',
    'Maximum performance mode',
    'Energy efficient mode',
    'Maximum energy saver mode',
    'Power saver mode updates',
    'Mode effects detailed information',
    'Idle power saver enable/disable',
    'Idle power saver delay time (seconds)',
    'Idle power saver utilization threshold (%)',
    'Enter idle power saver settings',
    'Exit idle power saver settings',
    'Reset idle power settings to default',
    'Power cap management',
    'Power consumption tracking',
    'Energy management modes',
    'Power optimization settings',
  ],

  // Searchable keywords
  keywords: [
    'power',
    'power cap',
    'power consumption',
    'current power consumption',
    'power cap setting',
    'apply power cap',
    'power cap value',
    'watts',
    'power limit',
    'power management',
    'performance mode',
    'power and performance mode',
    'maximum performance',
    'energy efficient',
    'maximum energy saver',
    'energy saver',
    'power saver',
    'power saver mode',
    'select mode',
    'update power saver mode',
    'enable maximum energy saver',
    'idle power saver',
    'enable idle power saver',
    'idle saver',
    'delay time',
    'delay time seconds',
    'utilization threshold',
    'threshold percentage',
    'enter delay time',
    'exit delay time',
    'enter utilization',
    'exit utilization',
    'update idle power saver',
    'reset to default',
    'reset idle power',
    'save power',
    'save changes',
    'successfully saved',
    'successfully updated',
    'successfully reset',
    'power settings',
    'power configuration',
    'energy',
    'power efficiency',
    'power policy',
    'power optimization',
    'dynamic power',
    'wattage',
    'power usage',
    'mode selection',
    'confirm selection',
    'cancel',
    'view detailed information',
    'arrow',
    'effects of mode',
  ],

  // Related terms
  relatedTerms: [
    'energy efficiency',
    'power control',
    'thermal management',
    'performance tuning',
    'power throttling',
    'energy savings',
    'power budget',
    'system performance',
    'power modes',
    'energy consumption',
    'power monitoring',
    'power limits',
    'idle management',
    'power thresholds',
    'system efficiency',
    'resource management',
  ],
};

export default powerSearchContent;
