export const memorySearchContent = {
  // Main description
  description:
    'View and manage system memory configuration including logical memory block size, system memory page setup with huge pages, I/O adapter enlarged capacity, dynamic I/O drawer attachment, active memory mirroring, and predictive dynamic memory deallocation',

  // Feature descriptions
  features: [
    'Logical memory block size configuration',
    'Memory block size for partitioning',
    'System memory page setup',
    'Huge pages configuration (16GB pages)',
    'Maximum number of huge pages',
    'Requested huge page memory',
    'I/O Adapter enlarged capacity',
    'PCIe memory space allocation',
    'Slot count configuration for Node 0',
    'Dynamic I/O drawer attachment',
    'Platform memory allocation during IPL',
    'Active memory mirroring for hypervisor',
    'Memory mirroring mode enable/disable',
    'Predictive dynamic memory deallocation',
    'Dynamic memory page removal',
    'Predictive memory failure handling',
    'Memory configuration updates',
    'System resource management',
    'Virtual memory page sizes',
    'PCIe slot memory allocation',
  ],

  // Searchable keywords
  keywords: [
    'memory',
    'logical memory block size',
    'memory block size',
    'partitioning',
    'system memory page',
    'huge pages',
    'virtual memory',
    '16GB pages',
    'max huge pages',
    'maximum number huge pages',
    'requested huge page memory',
    'I/O adapter',
    'enlarged capacity',
    'PCIe memory',
    'PCIe slot',
    'slot count',
    'node 0',
    'dynamic I/O',
    'drawer attachment',
    'IPL',
    'platform memory',
    'active memory mirroring',
    'memory mirroring',
    'hypervisor',
    'mirroring mode',
    'predictive deallocation',
    'dynamic deallocation',
    'memory deallocation',
    'predictive failure',
    'memory failure',
    'uncorrectable error',
    'memory page removal',
    'update memory',
    'memory settings',
    'memory configuration',
    'successfully updated',
    'enable mirroring',
    'disable mirroring',
    'memory management',
    'system resources',
    'performance improvement',
    'application performance',
  ],

  // Related terms
  relatedTerms: [
    'system resources',
    'hardware resources',
    'memory hardware',
    'physical memory',
    'memory allocation',
    'resource management',
    'system configuration',
    'memory optimization',
    'performance tuning',
    'PCIe configuration',
    'I/O configuration',
    'hypervisor memory',
    'memory protection',
    'error handling',
    'memory reliability',
    'system memory',
    'memory capacity',
  ],
};

export default memorySearchContent;
