export const inventorySearchContent = {
  // Main description
  description:
    'View and edit hardware inventory preferences including system indicators (power status, identify LED, attention LED, lamp test), chassis, system, BMC manager, DIMM slots, fans, power supplies, processors, assemblies, PCIe slots, and fabric adapters. Manage LED indicators for all components with detailed hardware information.',

  // Feature descriptions
  features: [
    'Hardware inventory viewing',
    'LED indicator management',
    'Chassis information',
    'Processor inventory',
    'Memory module inventory',
    'Fan inventory',
    'Power supply inventory',
    'BMC manager information',
    'System information',
    'Component status monitoring',
    'Service indicators',
    'Identify LEDs',
    'System indicators display',
    'Power status display',
    'System identify LED control',
    'System attention LED control',
    'Lamp test control',
    'Enable/disable identify LED',
    'Successfully enabled LED messages',
    'Chassis ID, Health, Status, Location number',
    'View Name and Firmware version',
    'System Serial number, Memory, Model, Processor count',
    'BMC manager Description, Part number, Serial number',
    'DIMM slot Capacity, Enabled status',
    'Fan Spare part number, Model information',
    'Power supply Firmware version',
    'Processor Type, Total cores',
    'Assembly Part number information',
    'PCIe slots Slot type',
    'Fabric Adapters Model, Serial number',
    'Click arrow to expand details',
    'FRU number (Spare part number)',
    'CCIN (Model) information',
  ],

  // Searchable keywords
  keywords: [
    'inventory',
    'LED',
    'LEDs',
    'hardware',
    'chassis',
    'processor',
    'memory',
    'fan',
    'power supply',
    'BMC',
    'system',
    'component',
    'hardware inventory',
    'LED indicator',
    'service indicator',
    'identify LED',
    'component inventory',
    'system inventory',
    'hardware status',
    'DIMM',
    'PCIe',
    'fabric adapter',
    'assembly',
    'system indicators',
    'power status',
    'system identify LED',
    'system attention LED',
    'lamp test',
    'enable LED',
    'disable LED',
    'LED on',
    'LED off',
    'successfully enabled',
    'successfully disabled',
    'identify LED on',
    'identify LED off',
    'attention LED on',
    'attention LED off',
    'lamp test on',
    'lamp test off',
    'chassis ID',
    'chassis health',
    'chassis status',
    'location number',
    'firmware version',
    'click arrow',
    'expand details',
    'serial number',
    'part number',
    'spare part number',
    'FRU number',
    'model',
    'CCIN',
    'total system memory',
    'processor count',
    'core count',
    'asset tag',
    'BMC manager',
    'OpenBmc Manager',
    'description',
    'DIMM slot',
    'memory module',
    'capacity MiB',
    'enabled status',
    'fans',
    'power supplies',
    'powersupply',
    'processors',
    'processor type',
    'total cores',
    'assemblies',
    'connector',
    'OpenCAPI Port',
    'PCIe slots',
    'slot type',
    'fabric adapters',
    'PCI adapter',
    'click identify LED',
    'set LED to on',
    'set LED to off',
    'default LED off',
    'default LED on',
    'view preferences',
    'edit preferences',
  ],

  // Related terms
  relatedTerms: [
    'hardware components',
    'system components',
    'component status',
    'hardware monitoring',
    'system monitoring',
    'component information',
    'hardware information',
    'LED management',
    'indicator control',
    'component details',
    'hardware details',
    'system health',
    'component health',
    'status monitoring',
    'location information',
    'version information',
    'expandable rows',
    'detailed view',
    'component specifications',
    'hardware specifications',
    'field replaceable unit',
    'customer card identification number',
    'memory capacity',
    'processor specifications',
    'power supply specifications',
    'fan specifications',
    'adapter specifications',
    'slot information',
    'assembly information',
  ],
};

export default inventorySearchContent;
