export const capacityOnDemandSearchContent = {
  // Main description
  description:
    'Manage capacity on demand activation with 34-character activation codes, view order information for on-demand utilities including system, processor, memory, and access key information, and manage VET capabilities with setting and bit capability status',

  // Feature descriptions
  features: [
    'Capacity on demand activation',
    'Activation code entry (34 characters)',
    'System power on requirement',
    'PHYP standby or running requirement',
    'Activate activation code',
    'Order information for on-demand utilities',
    'System information display',
    'System type and serial number',
    'System anchor and COD unique ID',
    'System COD public key',
    'Processor information display',
    'Processor resource ID',
    'Processor sequence number',
    'Processors licensed count',
    'Memory information display',
    'Memory resource ID',
    'Memory sequence number',
    'Memory licensed amount',
    'Access key information',
    'Firmware access key expiration',
    'AIX access key expiration',
    'VET capabilities management',
    'Setting and Bit capability status',
    'Resource dump creation',
    'Resource selector for dumps',
    'Access key from www.ibm.com/servers/eserver/ess',
  ],

  // Searchable keywords
  keywords: [
    'capacity',
    'on demand',
    'COD',
    'activation',
    'activation code',
    'enter activation code',
    '34 characters',
    'activate',
    'system powered on',
    'power on',
    'PHYP',
    'standby',
    'running',
    'license',
    'VET',
    'VET capabilities',
    'processor',
    'memory',
    'access key',
    'order information',
    'on-demand utilities',
    'system information',
    'system type',
    'system serial number',
    'serial number',
    'system anchor',
    'COD unique ID',
    'unique ID',
    'COD public key',
    'public key',
    'processor information',
    'processor resource ID',
    'resource ID',
    'processor sequence number',
    'sequence number',
    'processors licensed',
    'licensed processors',
    'memory information',
    'memory resource ID',
    'memory sequence number',
    'memory licensed',
    'licensed memory',
    'access key information',
    'firmware access key',
    'AIX access key',
    'access key expiration',
    'expiration',
    'setting',
    'bit capability',
    'capability status',
    'resource dump',
    'dumps',
    'resource selector',
    'www.ibm.com',
    'ibm.com/servers/eserver/ess',
    'obtain access key',
    'new access key',
    'capacity on demand',
    'processor license',
    'memory license',
    'trial license',
    'permanent license',
    'system COD',
    'resource activation',
    'COD activation',
    'applying changes',
    'more information',
    'not available',
  ],

  // Related terms
  relatedTerms: [
    'resource licensing',
    'system licensing',
    'feature activation',
    'capacity upgrade',
    'license management',
    'resource management',
    'system resources',
    'hardware activation',
    'system configuration',
    'processor allocation',
    'memory allocation',
    'key management',
    'expiration management',
    'system utilities',
    'resource information',
    'system details',
    'hardware licensing',
  ],
};

export default capacityOnDemandSearchContent;
