export const serverPowerOperationsSearchContent = {
  // Main description
  description:
    'Manage server power operations including power on, shutdown, reboot, boot settings, and BIOS configuration',

  // Feature descriptions
  features: [
    'Server power on',
    'Server shutdown',
    'Server reboot',
    'Orderly shutdown',
    'Immediate shutdown',
    'Orderly reboot',
    'Immediate reboot',
    'Server status monitoring',
    'Last power operation tracking',
    'One-time boot settings',
    'Boot settings configuration',
    'BIOS settings management',
    'PHYP standby mode',
    'OS running state',
    'Server firmware start policy',
    'Default partition environment',
    'AIX/Linux partition boot mode',
    'IBM i partition boot mode',
    'Server operating mode',
    'Server power policy',
    'Auto-start configuration',
    'Standby mode management',
    'Linux KVM configuration',
    'Network settings during boot',
  ],

  // Searchable keywords
  keywords: [
    'power',
    'server',
    'operations',
    'power on',
    'power off',
    'shutdown',
    'reboot',
    'restart',
    'orderly',
    'immediate',
    'boot',
    'BIOS',
    'settings',
    'status',
    'chassis',
    'PHYP',
    'standby',
    'runtime',
    'OS running',
    'operating system',
    'server power',
    'power operations',
    'server shutdown',
    'server reboot',
    'orderly shutdown',
    'immediate shutdown',
    'orderly reboot',
    'immediate reboot',
    'power status',
    'server status',
    'boot settings',
    'BIOS settings',
    'one-time boot',
    'firmware start',
    'partition',
    'AIX',
    'Linux',
    'IBM i',
    'KVM',
    'auto-start',
    'manual mode',
    'normal mode',
    'operating mode',
    'power policy',
    'stay on',
    'power off',
    'automatic',
    'default partition',
    'partition environment',
    'boot mode',
    'load source',
    'console',
    'system memory',
    'HMC',
    'ASMI',
    'recovery power',
    'abnormal termination',
    'auto power restart',
    'system termination',
  ],

  // Related terms
  relatedTerms: [
    'chassis power',
    'system power',
    'power management',
    'server management',
    'power control',
    'system control',
    'graceful shutdown',
    'forced shutdown',
    'graceful reboot',
    'forced reboot',
    'system restart',
    'cold boot',
    'warm boot',
    'power cycle',
    'system state',
    'power state',
    'boot configuration',
    'startup settings',
    'firmware configuration',
    'partition management',
    'hypervisor',
    'virtualization',
    'system firmware',
    'boot loader',
    'boot device',
    'boot priority',
    'system initialization',
  ],
};

export default serverPowerOperationsSearchContent;
