export const serverPowerOperationsSearchContent = {
  // Main description
  description:
    'View and edit server power preferences including current status, power operations (power on, reboot, shutdown), and settings for operating mode, power policy, and firmware start policy. Network settings available for Non-HMC managed systems in PHYP standby with IBM i or Default partition environment.',

  // Feature descriptions
  features: [
    'Server power on',
    'Server shutdown',
    'Server reboot',
    'Orderly shutdown',
    'Immediate shutdown',
    'Orderly reboot',
    'Immediate reboot',
    'Server status monitoring',
    'Last power operation tracking',
    'One-time boot settings',
    'Boot settings configuration',
    'BIOS settings management',
    'PHYP standby mode',
    'OS running state',
    'Server firmware start policy',
    'Default partition environment',
    'AIX/Linux partition boot mode',
    'IBM i partition boot mode',
    'Server operating mode',
    'Server power policy',
    'Auto-start configuration',
    'Standby mode management',
    'Linux KVM configuration',
    'Network settings during boot',
    'View current server status',
    'Display last chassis power operation',
    'Click Power on to enable power',
    'No options during power operation in progress',
    'Reboot server with confirmation',
    'Click Reboot to restart server',
    'Click Confirm or Cancel',
    'Shutdown server with options',
    'Orderly shutdown - OS shuts down first',
    'Immediate shutdown - may cause data corruption',
    'Click Shut down to shutdown server',
    'Server operating mode selection',
    'Normal - Automatic mode',
    'Manual - Service/Maintenance mode',
    'Server power policy selection',
    'Power Off - server powers off with last partition',
    'Stay On - server stays on after last partition',
    'Automatic - behavior based on partitioning',
    'Server firmware start policy selection',
    'Auto-start always option',
    'Standby (User-initiated) option',
    'Auto-start only option',
    'Click Save to save changes',
    'View power setting descriptions',
    'Network settings for Non-HMC managed systems',
  ],

  // Searchable keywords
  keywords: [
    'power',
    'server',
    'operations',
    'power on',
    'power off',
    'shutdown',
    'reboot',
    'restart',
    'orderly',
    'immediate',
    'boot',
    'BIOS',
    'settings',
    'status',
    'chassis',
    'PHYP',
    'standby',
    'runtime',
    'OS running',
    'operating system',
    'server power',
    'power operations',
    'server shutdown',
    'server reboot',
    'orderly shutdown',
    'immediate shutdown',
    'orderly reboot',
    'immediate reboot',
    'power status',
    'server status',
    'boot settings',
    'BIOS settings',
    'one-time boot',
    'firmware start',
    'partition',
    'AIX',
    'Linux',
    'IBM i',
    'KVM',
    'auto-start',
    'manual mode',
    'normal mode',
    'operating mode',
    'power policy',
    'stay on',
    'power off',
    'automatic',
    'default partition',
    'partition environment',
    'boot mode',
    'load source',
    'console',
    'system memory',
    'HMC',
    'ASMI',
    'recovery power',
    'abnormal termination',
    'auto power restart',
    'system termination',
    'view preferences',
    'edit preferences',
    'current status',
    'server status display',
    'last chassis power operation',
    'click power on',
    'enable power',
    'power operation in progress',
    'no options displayed',
    'reboot server',
    'click reboot',
    'restart server',
    'click confirm',
    'click cancel',
    'shutdown server',
    'shutdown options',
    'orderly OS shutdown',
    'operating system shuts down',
    'immediate server shutdown',
    'data corruption',
    'click shut down',
    'server operating mode',
    'normal automatic',
    'manual service',
    'maintenance mode',
    'server power policy',
    'power off policy',
    'stay on policy',
    'automatic policy',
    'last partition',
    'partitioned system',
    'non-partitioned system',
    'firmware start policy',
    'auto-start always',
    'standby user-initiated',
    'auto-start only',
    'click save',
    'save changes',
    'view power setting descriptions',
    'detailed descriptions',
    'network settings',
    'non-HMC managed',
    'PHYP standby',
    'IBM i partition',
    'default partition',
  ],

  // Related terms
  relatedTerms: [
    'chassis power',
    'system power',
    'power management',
    'server management',
    'power control',
    'system control',
    'graceful shutdown',
    'forced shutdown',
    'graceful reboot',
    'forced reboot',
    'system restart',
    'cold boot',
    'warm boot',
    'power cycle',
    'system state',
    'power state',
    'boot configuration',
    'startup settings',
    'firmware configuration',
    'partition management',
    'hypervisor',
    'virtualization',
    'system firmware',
    'boot loader',
    'boot device',
    'boot priority',
    'system initialization',
    'preferences management',
    'status monitoring',
    'operation tracking',
    'power enable',
    'operation progress',
    'confirmation dialog',
    'cancel operation',
    'shutdown methods',
    'OS shutdown',
    'server shutdown',
    'data integrity',
    'corruption risk',
    'mode selection',
    'automatic mode',
    'service mode',
    'maintenance operations',
    'policy configuration',
    'power behavior',
    'partition behavior',
    'system partitioning',
    'start policy',
    'user-initiated start',
    'automatic start',
    'save configuration',
    'setting descriptions',
    'HMC management',
    'managed systems',
    'unmanaged systems',
    'standby state',
    'partition type',
  ],
};

export default serverPowerOperationsSearchContent;
