export const hostConsoleSearchContent = {
  // Main description
  description:
    'View and control the server console over the network, independent of the operating system. View the status of the server console and open it in a new tab for better accessibility.',

  // Feature descriptions
  features: [
    'Serial port console access',
    'Terminal emulation',
    'Console output monitoring',
    'Server console interface',
    'Serial console redirection',
    'Command line interface access',
    'System console viewer',
    'Remote console access',
    'Console log viewer',
    'Text-based console',
    'Host system terminal',
    'Serial over LAN console',
    'View and control server console',
    'Network-based console access',
    'Operating system independent console',
    'View server console status',
    'Open console in new tab',
    'Display status in new window',
    'Click Host console to access',
    'Console status display',
  ],

  // Searchable keywords
  keywords: [
    'SOL',
    'Serial over LAN',
    'terminal',
    'console',
    'serial',
    'output',
    'monitor',
    'viewer',
    'access',
    'remote',
    'interface',
    'command line',
    'shell',
    'CLI',
    'host',
    'server console',
    'system console',
    'serial port',
    'text console',
    'console log',
    'terminal emulator',
    'remote console',
    'console access',
    'serial console',
    'host console',
    'console viewer',
    'console monitor',
    'console output',
    'serial output',
    'terminal access',
    'terminal viewer',
    'view server console',
    'control server console',
    'console over network',
    'network console',
    'operating system independent',
    'OS independent',
    'independent of OS',
    'view status',
    'console status',
    'server console status',
    'status display',
    'open in new tab',
    'new tab',
    'new window',
    'display in new window',
    'click host console',
    'click open',
    'open console',
    'console new tab',
    'status new window',
  ],

  // Related terms
  relatedTerms: [
    'server management',
    'system administration',
    'remote management',
    'console management',
    'serial communication',
    'terminal session',
    'console session',
    'host management',
    'system monitoring',
    'console redirection',
    'Web socket',
    'network-based access',
    'OS-independent access',
    'platform independent',
    'console control',
    'server control',
    'status monitoring',
    'console window',
    'separate window',
    'tab management',
    'window management',
    'console interface',
    'network interface',
    'remote control',
  ],
};

export default hostConsoleSearchContent;
