export const firmwareSearchContent = {
  // Main description
  description:
    'View firmware versions of BMC and server including running and backup images. Switch between images to activate selected firmware. Update firmware by uploading files and manage access key expiration for firmware updates.',

  // Feature descriptions
  features: [
    'BMC firmware management',
    'Server firmware management',
    'PNOR firmware management',
    'System firmware updates',
    'Firmware image upload from workstation',
    'Image activation and boot priority',
    'Running image management',
    'Backup image management',
    'Functional image control',
    'Active image management',
    'Boot order configuration',
    'Automatic BMC reboot after activation',
    'Manual BMC reboot option',
    'Server power operations integration',
    'Multi-step firmware activation process',
    'Image state monitoring',
    'Failed image recovery',
    'Ready image activation',
    'Invalid image detection',
    'Code update',
    'BMC images table',
    'Server images table',
    'View firmware version of BMC and server',
    'Running image version and status display',
    'Backup image version and status display',
    'Switch to running image activation',
    'BMC reboot required for backup image',
    'Application unresponsive during switch',
    'Switch images to change firmware',
    'Cancel image switch operation',
    'Update firmware option',
    'Add file to upload firmware',
    'Start update to begin firmware update',
    'Access key expiration display',
    'Manage access key to obtain new key',
  ],

  // Searchable keywords
  keywords: [
    'firmware',
    'BMC',
    'server',
    'PNOR',
    'image',
    'upload',
    'download',
    'activate',
    'boot',
    'priority',
    'functional',
    'active',
    'activating',
    'failed',
    'ready',
    'invalid',
    'running',
    'backup',
    'workstation',
    'reboot',
    'power',
    'system firmware',
    'BMC firmware',
    'server firmware',
    'PNOR firmware',
    'firmware update',
    'firmware upgrade',
    'image file',
    'boot priority',
    'boot order',
    'image state',
    'functional image',
    'active image',
    'running image',
    'backup image',
    'activate firmware',
    'upload firmware',
    'download firmware',
    'image upload',
    'image download',
    'firmware activation',
    'automatic reboot',
    'manual reboot',
    'BMC reboot',
    'server reboot',
    'power operations',
    'image management',
    'firmware management',
    'boot management',
    'failed image',
    'ready image',
    'invalid image',
    'activating image',
    'firmware file',
    'image table',
    'BMC images',
    'server images',
    'code update',
    'arrow icons',
    'boot device',
    'device boot',
    'image states',
    'file name',
    'choose file',
    'activate continue',
    'without rebooting',
    'automatically reboot',
    'view firmware version',
    'firmware version BMC',
    'firmware version server',
    'running image version',
    'running image status',
    'backup image version',
    'backup image status',
    'switch to running',
    'activate selected image',
    'BMC reboot required',
    'application unresponsive',
    'switch images',
    'change images',
    'cancel switch',
    'update firmware option',
    'add file',
    'upload firmware file',
    'start update',
    'start firmware update',
    'access key expiration',
    'expiration date',
    'manage access key',
    'obtain new access key',
    'new access key',
    'click switch to running',
    'click switch images',
    'click cancel',
    'click add file',
    'click start update',
    'click manage access key',
  ],

  // Related terms
  relatedTerms: [
    'system update',
    'software update',
    'firmware flash',
    'image flash',
    'boot loader',
    'BIOS update',
    'UEFI update',
    'system maintenance',
    'version control',
    'patch management',
    'firmware rollback',
    'image rollback',
    'recovery image',
    'golden image',
    'factory image',
    'system image',
    'boot configuration',
    'startup image',
    'primary image',
    'secondary image',
    'image switching',
    'firmware switching',
    'version management',
    'update process',
    'activation process',
    'reboot process',
    'trivial file transfer protocol',
    'file transfer',
    'remote upload',
    'local upload',
    'system errors',
    'firmware combination',
    'version display',
    'status display',
    'image selection',
    'selected image',
    'reboot requirement',
    'temporary unavailability',
    'unresponsive application',
    'image change',
    'firmware change',
    'cancel operation',
    'file upload',
    'firmware file upload',
    'update initiation',
    'key expiration',
    'access key management',
    'key renewal',
    'obtain key',
    'new key',
    'expiration information',
    'firmware window',
    'image window',
  ],
};

export default firmwareSearchContent;
