/**
 * Firmware Search Content
 *
 * This file contains searchable keywords and descriptions for the Firmware page.
 * These terms will be indexed by the search utility to make the Firmware page
 * discoverable when users search in the header search bar.
 */

export const firmwareSearchContent = {
  // Main description
  description:
    'Manage BMC and server firmware images, upload and activate firmware files, control boot priority and image states',

  // Feature descriptions
  features: [
    'BMC firmware management',
    'Server firmware management',
    'PNOR firmware management',
    'System firmware updates',
    'Firmware image upload from workstation',
    'Image activation and boot priority',
    'Running image management',
    'Backup image management',
    'Functional image control',
    'Active image management',
    'Boot order configuration',
    'Automatic BMC reboot after activation',
    'Manual BMC reboot option',
    'Server power operations integration',
    'Multi-step firmware activation process',
    'Image state monitoring',
    'Failed image recovery',
    'Ready image activation',
    'Invalid image detection',
    'Code update',
    'BMC images table',
    'Server images table',
  ],

  // Searchable keywords
  keywords: [
    'firmware',
    'BMC',
    'server',
    'PNOR',
    'image',
    'upload',
    'download',
    'activate',
    'boot',
    'priority',
    'functional',
    'active',
    'activating',
    'failed',
    'ready',
    'invalid',
    'running',
    'backup',
    'workstation',
    'reboot',
    'power',
    'system firmware',
    'BMC firmware',
    'server firmware',
    'PNOR firmware',
    'firmware update',
    'firmware upgrade',
    'image file',
    'boot priority',
    'boot order',
    'image state',
    'functional image',
    'active image',
    'running image',
    'backup image',
    'activate firmware',
    'upload firmware',
    'download firmware',
    'image upload',
    'image download',
    'firmware activation',
    'automatic reboot',
    'manual reboot',
    'BMC reboot',
    'server reboot',
    'power operations',
    'image management',
    'firmware management',
    'boot management',
    'failed image',
    'ready image',
    'invalid image',
    'activating image',
    'firmware file',
    'image table',
    'BMC images',
    'server images',
    'code update',
    'arrow icons',
    'boot device',
    'device boot',
    'image states',
    'file name',
    'choose file',
    'activate continue',
    'without rebooting',
    'automatically reboot',
  ],

  // Related terms
  relatedTerms: [
    'system update',
    'software update',
    'firmware flash',
    'image flash',
    'boot loader',
    'BIOS update',
    'UEFI update',
    'system maintenance',
    'version control',
    'patch management',
    'firmware rollback',
    'image rollback',
    'recovery image',
    'golden image',
    'factory image',
    'system image',
    'boot configuration',
    'startup image',
    'primary image',
    'secondary image',
    'image switching',
    'firmware switching',
    'version management',
    'update process',
    'activation process',
    'reboot process',
    'trivial file transfer protocol',
    'file transfer',
    'remote upload',
    'local upload',
    'system errors',
    'firmware combination',
  ],
};

export default firmwareSearchContent;
